[package]
name = "bank"
version = "0.1.0"
edition = "2021"

[dependecies]

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
tokio-postgres = "0.7.10"
protocol = { path = "../protocol" }
